<!DOCTYPE html>
<html>
    <head>
        <!--[if lt IE 9]>
        <script type="text/javascript" src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <link type="text/css" rel="stylesheet" href="third-party/jquery-ui/css/jquery-ui-1.8.16.custom.css"/>
        <link type="text/css" rel="stylesheet" href="third-party/bootstrap/css/bootstrap.css">
        <link type="text/css" rel="stylesheet" href="third-party/jquery-ui-date-range-picker/css/ui.daterangepicker.css" media="screen" />
        <link type="text/css" rel="stylesheet" href="third-party/wijmo/css/jquery.wijmo-open.1.5.0.css" />
        <link type="text/css" rel="stylesheet" href="third-party/jquery-ui-fileinput/css/enhanced.css">

        <link type="text/css" rel="stylesheet" href="css/moe_base.css" >
        <link type="text/css" rel="stylesheet" href="css/moe_components.css" >

    </head>

    <body>
        <!--[if IE]>
        <link rel="stylesheet" type="text/css" href="third-party/jquery-ui/css/jquery.ui.1.8.16.ie.css"/>
        <![endif]-->

        <!-- El Codigo Empieza Aqui -->
        <div id="head">
            <button class="izq" onmousedown="$('#content').moeAjax('index/login');">Home</button>
            <button class="der" onmousedown="$('#content').moeAjax('test/test');">Test</button>
            <button class="der" onmousedown="$('#content').moeAjax('test/showcase');">Showcase</button>
        </div>
        <div id="main">
            <div id="content">

            </div>
        </div>
        <div id="foot">

        </div>

        <div id="indicador_ajax"></div>
        <div id="mensajes_notificador"></div>
        
        <!-- El Codigo Termina Aqui -->
        <script src="third-party/require-js/js/require.js"></script>
        <script type="text/javascript">
            (function(){
                function $(s){return "third-party/require-js/js/order!" + s;}
                
                require({
                    waitSeconds : 15,
                    paths: {
                        jquery : "third-party/jquery/js/jquery",
                        jquery_ui : "third-party/jquery-ui/js/jquery-ui",
                        validador : "third-party/jquery-validate/jquery.validate.min",
                        auto_numerico : "third-party/jquery-auto-numeric/auto-numeric.min",
                        mascara : "third-party/jquery-masked-input/jquery.maskedinput-1.3.min"
                    }
                });
                
                require([$("jquery"), $("jquery_ui"), $("third-party/wijmo/js/jquery.wijmo-open.1.5.0.min.js")]);
                require([$("jquery"), $("third-party/jquery-nextto/jquery.nextTo.min.js")]);
                require([$("jquery"), $("third-party/wijmo/js/jquery.mousewheel.min.js")]);
                require([$("jquery"), $("third-party/wijmo/js/jquery.bgiframe-2.1.3-pre.js")]);
                require([$("jquery"), $("third-party/jquery-ui-fileinput/js/enhance.min.js")]);
                require([$("jquery"), $("third-party/jquery-ui-fileinput/js/fileinput.jquery.js")]);
                require([$("jquery"), $("third-party/jquery-ui-date-range-picker/js/date.js")]);
                require([$("jquery"), $("third-party/jquery-ui-date-range-picker/js/daterangepicker.jquery.js")]);
                require([$("jquery"), $("validador"), $("third-party/jquery-validate/messages_es.js")]);
                require([$("jquery"), $("auto_numerico")]);
                require([$("jquery"), $("mascara")]);
                require([$("jquery"), $("js/main")]);
            })();
        </script>
    </body>
</html>


