<center>
    <div id="login">
        <table>
            <tbody>
                <tr>
                    <td colspan="2" class="titulo">
                        <?php echo $this->translate("moe"); ?>
                    </td>
                </tr>
                <tr>
                    <td class="etiqueta">
                        <?php echo $this->translate("usuario"); ?>:</td>
                    <td>
                        <input />
                    </td>
                </tr>
                <tr>
                    <td class="etiqueta">
                        <?php echo $this->translate("clave"); ?>:</td>
                    <td>
                        <input />
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <button class="boton_login">
                            <?php echo $this->translate("ingresar"); ?>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>



    <div id="errores_validacion" style="display: none;">
        <br/>
        <br/>
        <br/>
    </div>
</center>